#
# Your Crowdin credentials
#
project_id: "592303"
api_token_env: CROWDIN_PERSONAL_TOKEN
#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files:
    - source: "/i18n/en/*"
      translation: "/i18n/%two_letters_code%/%original_file_name%"
    - source: "/i18n/en/docusaurus-plugin-content-docs/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/%original_file_name%"
    - source: "/i18n/en/docusaurus-theme-classic/*"
      translation: "/i18n/%two_letters_code%/docusaurus-theme-classic/%original_file_name%"

    - source: "/docs/00_intro/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/00_intro/%original_file_name%"
    - source: "/docs/10_domains/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/10_domains/%original_file_name%"
    - source: "/docs/20_role/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/20_role/%original_file_name%"
    - source: "/docs/30_data/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/30_data/%original_file_name%"
    - source: "/docs/40_smartlab/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/40_smartlab/%original_file_name%"
    - source: "/docs/50_data_publication/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/50_data_publication/%original_file_name%"
    - source: "/docs/50_data_publication/51_lbe/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/50_data_publication/51_lbe/%original_file_name%"
    - source: "/docs/60_topics/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/60_topics/%original_file_name%"
    - source: "/docs/60_topics/61_identifiers/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/60_topics/61_identifiers/%original_file_name%"
    - source: "/docs/60_topics/62_data_formats/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/60_topics/62_data_formats/%original_file_name%"
    - source: "/docs/60_topics/63_data_description_annotation/*"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/60_topics/63_data_description_annotation/%original_file_name%"
    - source: "/src/pages/*.(md|mdx)"
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-pages/%original_file_name%"
