#
# Your Crowdin credentials
#
project_id: "592303"
api_token_env: CROWDIN_PERSONAL_TOKEN
#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files:
  - source: "/i18n/en/**/*"
    translation: "/i18n/%two_letters_code%/**/%original_file_name%"
  - source: "/docs/**/*"
    translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%"